### ISSUE TITLE
Terraform: v2.6以降の更新の反映

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/docs.usacloud.jp#75]
TerraformプロバイダーのCHANGELOGより未反映なものを抜粋

## 2.10.0 (Unreleased)

FEATURES

- [x] Enhanced Database [GH-847]
- [x] SimpleMonitor: timeout [GH-850]
- [x] ELB: supports syslog block and ssl_policy field [GH-849]

## 2.9.3 (2021-06-29)

- [x] Moved default size setting from the schema definition section #80

## 2.9.0 (2021-06-15)

- [x] LoadBalancer: Increased VIP limit to 20 #80
- [x] VPCRouter: WireGuard server #80
- [x] ELB: extending rule-based-balancing #80

## 2.8.4(2021-05-02)

* [x] Remove bucket_object resources #79
* [x] sakuracloud_proxylb_acme: subject_alt_names #79

## 2.8.3(2021-04-12)

FEATURES:

  * [x] simple_monitor: contains_string & proxylb: gzip #79

## 2.8.2(2021-04-01)

FEATURES:

  * [x] simple_monitor: http2 [GH-813] #79

## 2.8.1(2021-03-26)

  * [x] Fix packet_filter examples #79

## 2.8.0(2021-03-22)

  * [x] sakuracloud_server: ssh_keys #79
  * [x] sakuracloud_sim: Sentitive:true #79
  * [x] upgrade dependencies - libsacloud to v2.14.1 - added internet plans #79

## 2.7.0 (2021-01-16)

* [x] VPCRouter version #56 #78
* [x] Added support for parameters blocks in sakuracloud_database #78

## 2.6.0 (2021-01-05)

* [x] WebAccelerator #55 #76
